version: '3.0'

services:
    app:
        build:
            context: docker/php
            args:
                - ENABLE_XDEBUG=${ENABLE_XDEBUG:-false}
            dockerfile: ./8.1/Dockerfile
        working_dir: /var/www
        volumes:
            - "./:/var/www"
            - ./docker/php/app.ini:/usr/local/etc/php/conf.d/app.ini
        links:
            - mysql
        environment:
            PHP_EXTENSION_XDEBUG: 1
        extra_hosts:
            - "host.docker.internal:host-gateway"
    nginx:
        build:
            context: docker/nginx
            dockerfile: ./Dockerfile
        working_dir: /var/www
        volumes:
            - "./:/var/www"
            - ./docker/php/app.ini:/usr/local/etc/php/conf.d/app.ini
        depends_on:
            - app
        ports:
            - ${WEB_PORT:-80}:80
        extra_hosts:
            - "host.docker.internal:host-gateway"
    mysql:
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password  --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=NO_ENGINE_SUBSTITUTION --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
        ports:
            - ${MYSQL_PORT:-3306}:3306
        hostname: mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
        volumes:
            - "./docker/db_data:/var/lib/mysql"
    phpmyadmin:
        build:
            context: docker/phpmyadmin
            dockerfile: ./Dockerfile
        depends_on:
            - mysql
        ports:
            - ${PMA_PORT:-81}:80
        environment:
            PMA_ARBITRARY: 0
            PMA_HOST: mysql
            MYSQL_USER: ${DB_USERNAME:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
